9 implement a sample for mvvm
viamgr/trainingapp pull request #14
Opened 2023-09-01 11:41 UTC by pariami

Create unit test for SampleViewModel

2023-09-03 19:08 UTC, viamgr requested changes

2023-09-03 19:08 UTC, viamgr commented on app/build.gradle.kts
> +    androidTestImplementation ("com.github.blocoio:faker:2.0.1")
There is no need to use the faker library. We can use it in the future but not now.

2023-09-03 19:08 UTC, viamgr commented on app/src/main/java/msi/paria/trainingapp/MainActivity.kt
> +
I think this is an unreasonable change.

2023-09-03 19:08 UTC, viamgr commented on app/src/test/java/msi/paria/trainingapp/SampleViewModelTest.kt
> +        faker = Faker()
There is no need to use the faker library yet.

2023-09-03 19:08 UTC, viamgr commented on app/src/test/java/msi/paria/trainingapp/SampleViewModelTest.kt
> +    lateinit var email : String
I think you can define email locally instead of defining it globally here.

2023-09-03 19:08 UTC, viamgr commented on app/src/test/java/msi/paria/trainingapp/SampleViewModelTest.kt
> +        email = faker.internet.email()
I think you can use a local variable here instead of initiating that field.

2023-09-03 19:08 UTC, viamgr commented on app/src/test/java/msi/paria/trainingapp/SampleViewModelTest.kt
> +    fun test_email_isWrong() {
You can use a better function name for this test. for example: GivenWrongEmail_WhenEmaileChangedAndSubmitClicked_ThenValidationShouldBeFalse

2023-09-03 19:08 UTC, viamgr commented on app/src/test/java/msi/paria/trainingapp/SampleViewModelTest.kt
> +    fun test_email_isEmpty() {
The test name should be better. you can use GWT style based on the previous example

2023-09-03 19:08 UTC, viamgr commented on app/src/test/java/msi/paria/trainingapp/SampleViewModelTest.kt
> +    fun test_email_isCorrect_button_not_clicked() {
The test names should explicitly represent what you test.

2023-09-03 19:08 UTC, viamgr commented on app/src/test/java/msi/paria/trainingapp/SampleViewModelTest.kt
> +    fun test_email_isCorrect_email_changed_not_received() {
Change the test function name.

2023-09-03 19:08 UTC, viamgr commented on app/src/test/java/msi/paria/trainingapp/SampleViewModelTest.kt
> +    fun test_multiple_email_entered() {
Change the test function name.

2023-09-03 19:08 UTC, viamgr commented on app/src/test/java/msi/paria/trainingapp/SampleViewModelTest.kt
> +    fun test_several_time_button_clicked() {
Change the test function name.

2023-09-03 19:08 UTC, viamgr commented on app/src/test/java/msi/paria/trainingapp/SampleViewModelTest.kt
> +    fun test_several_time_button_clicked_and_email_not_changed() {
Change the test function name.

2023-09-04 20:41 UTC, viamgr commented on app/src/test/java/msi/paria/trainingapp/SampleViewModelTest.kt
> +        email = "pariamsi.m7616@gmial.com"
You are not reacting with the view model here. I mean if you change the email locally and do not inform the view model about this change, it doesn't make sense.

2023-09-07 07:51 UTC, ms-dehghani commented on settings.gradle.kts
> +
Remove empty line please

2023-09-07 07:51 UTC, ms-dehghani commented on settings.gradle.kts
> +
Remove empty line please

2023-09-07 18:45 UTC, viamgr requested changes

2023-09-07 18:45 UTC, viamgr commented on app/build/intermediates/dex/debug/mergeExtDexDebug/classes.dex
Ignore and remove this file from the git source

2023-09-07 18:45 UTC, viamgr commented on app/build/intermediates/dex/debug/mergeExtDexDebug/classes2.dex
Ignore and remove this file from the git source

2023-09-07 18:45 UTC, viamgr commented on app/build/intermediates/merged_manifest/debug/AndroidManifest.xml
Remove this file from the git source

2023-09-07 18:45 UTC, viamgr commented on app/build/intermediates/merged_manifests/debug/AndroidManifest.xml
Ignore and remove this file from the git source

2023-09-07 18:45 UTC, viamgr commented on app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml
Ignore and remove this file from the git source

2023-09-08 18:08 UTC, viamgr approved these changes
Nice job

2023-09-08 18:09 UTC, merged