21 setup hilt
viamgr/trainingapp pull request #23
Opened 2023-09-26 13:54 UTC by pariami

//set hilt for ViewModel

2023-09-26 19:13 UTC, ms-dehghani commented on app/src/main/java/com/training/app/trainingapp/main/view_model/RegisterViewModel.kt
> +@HiltViewModel
Please add line break hear

2023-09-26 19:14 UTC, ms-dehghani requested changes

2023-09-26 19:14 UTC, ms-dehghani commented on app/build.gradle.kts
Please remove extra line break

2023-09-29 04:37 UTC, ms-dehghani approved these changes

2023-09-30 18:33 UTC, viamgr approved these changes

2023-09-30 18:33 UTC, merged