-connect domain layer to Forget Password ViewModel
viamgr/trainingapp pull request #43
Opened 2023-11-05 16:21 UTC by pariami

-use state for holding ForgetPasswordViewModel values
 -use event for getting user's action from ui
-use effect for showing result of viewModel functions on ui

2023-11-20 16:16 UTC, viamgr requested changes

2023-11-20 16:16 UTC, viamgr commented on app/build.gradle.kts
> +    implementation("org.mockito:mockito-core:3.4.6")
Instead of mockkito I think you can use a better library called mockk.

2023-11-20 16:16 UTC, viamgr commented on data/authorization/src/main/java/com/training/app/data/authorization/forgetpassword/repo/ForgetPasswordRepositoryImpl.kt
> +class ForgetPasswordRepositoryImpl @Inject constructor(private val dataProvider: ForgetPasswordDataProvider) : ForgetPasswordRepository {
Why did you remove the internal keyword?

2024-01-08 10:59 UTC, pariami commented
i merged this branch with branch 39 (add compose navigation)

2024-01-08 10:59 UTC, closed without merging